#!/bin/bash


path=$(realpath 0-current_working_directory)


echo ‘The absolute path is’ $path /root/Shell/basics/




echo ‘-----------------------------------’



DIR_PATH=$(dirname $path)



echo ‘The directory path is’ $DPATH /Shell/basics/
